name: build
on:
  push:
    branches:
      - dev
  workflow_call:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
    steps:
      - name: Checkout Site
        uses: actions/checkout@v2
        with:
          ref: dev
          path: codeholics
      - name: Checkout Plugins
        uses: actions/checkout@v2
        with:
          repository: Codeholics/pelican-plugins
          path: pelican-plugins
      - name: Build Content
        run: |
          cd codeholics
          pip install --upgrade pip
          pip install -r requirements.txt
          pelican ./content
