name: build
on:
  push:
    branches:
      - dev
  pull_request:
    branches: [ dev ]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Site
        uses: actions/checkout@v2
        with:
          ref: dev
          path: codeholics
      - name: Checkout Plugins
        uses: actions/checkout@v2
        with:
          repository: Codeholics/pelican-plugins
          path: pelican-plugins
      - name: Build Content
        run: |
          cd codeholics
          pip install -r requirements.txt
          pelican ./content
      - name: copy files to dev.codeholics.com
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          rsh: -oHostKeyAlgorithms=+ssh-rsa
          path: "output/*"
          remote_host: ${{ secrets.HOST }}
          remote_port: ${{ secrets.PORT }}
          remote_path: ${{ secrets.DEV_PATH }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.KEY }}
          remote_key_pass: ${{ secrets.PASSPHRASE }}
