on:
  push:
    branches:
     - 'dev'
jobs:
  build:
    uses: Codeholics/codeholics/.github/workflows/build.yml@dev
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Site
        uses: actions/checkout@v7
        with:
          ref: dev
          path: codeholics
      - name: Checkout Plugins
        uses: actions/checkout@v7
        with:
          repository: Codeholics/pelican-plugins
          path: pelican-plugins
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - name: Sync dependencies
        working-directory: codeholics
        run: uv sync
      - name: Build Content
        working-directory: codeholics
        run: uv run pelican -s pelicanconf.py
      - name: Copy files to dev.codeholics.com
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          timeout: 120s
          command_timeout: 10m
          debug: true
          source: "codeholics/output/*"
          #target: ${{ secrets.DEV_PATH }}
          target: "/home/codeholi/"
          strip_components: 2
          rm: true
          overwrite: true
